### ISSUE TITLE
Allow Twig in fields (allow_twig: true)

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2568] opened 2021-05-10 13:19 UTC
Hi!

Even though there is documentation about this, for exmaple https://docs.bolt.cm/4.0/fields/html#options, it seems not to be implemented yet.

At this moment setting the option `allow_twig: true` in a Contenttype `html`, `textarea` or `text` field and adding some content with Twig code in it, just renders the Twig code as plain text.

**Comment by bobdenotter** [comment] 2021-05-13 07:28
I think it should work.. I'll dig in!

**Comment by I-Valchev** [comment] 2021-05-14 11:19
Hi @nestordedios, not able to reproduce this yet. Do you know what version of Bolt? Let's see if we can take a look at an example! :-)

**Comment by nestordedios** [comment] 2021-05-17 10:08
Hi @bobdenotter and @I-Valchev , thanks for the reply. 

Indeed it seems to be working. It seems I configured it wrong in the first place.

**Comment by I-Valchev** [comment] 2021-05-17 10:15
Nice that you got it working! Let's close this issue then, see if it comes up again!

**Closed by I-Valchev** 2021-05-17 10:15 UTC
Labels: 🐛 tag: bug
