### ISSUE TITLE
`{% setcontent %}` tag should work with relative dates

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1608] opened 2020-07-06 07:52 UTC
```twig
{% setcontent myarticles = 'entries' where { status: 'published', publishedAt: '< last monday' } %}
```

**Comment by bobdenotter** [comment] 2020-07-06 07:53
Duplicate of #1417 

(which i was pretty sure I fixed, but apparently not)

**Comment by I-Valchev** [comment] 2020-07-06 07:55
hmm... maybe you did, but it doesn't work with the content dates? Or maybe I'm stupid and can't make it work.

**Comment by bobdenotter** [comment] 2020-07-06 07:58
No, it's broken alright.. I fixed it, but either my fix was wrong, or it got broken again.

**Comment by bobdenotter** [comment] 2020-07-10 11:12
The issue here is the space between `<` and `last monday`.. PR incoming!

**Closed** 2020-07-10 11:39 UTC
Labels: 🐛 tag: bug fix
