### ISSUE TITLE
Refactor: Apply #2322 to `master`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2337] opened 2021-01-23 11:55 UTC
Since 4.2 no longer has the file `ProfileController.php`, the change in #2322 was at least partially lost during merging 4.1 into master.

**Comment by I-Valchev** [comment] 2021-02-01 10:20
Looking at this, the part that was lost in `ProfileController.php` is about the `UserEvent::ON_POST_SAVE`. This is already dispatched for the `UserEditController.php` here:
https://github.com/bolt/core/blob/668b2754d7268005a6227a684f26c49a29c301e6/src/Controller/Backend/UserEditController.php#L209-L210

Since I also can't reproduce the bug (it works correctly), let's close this one as resolved. :-)

**Closed by I-Valchev** 2021-02-01 10:20 UTC
Labels: 🎩 refactor
