### ISSUE TITLE
secondary locale slugs appear editable when slug->localize is false

### ISSUE THREAD

**Issue by 0spinboson** [bolt/core#1114] opened 2020-02-22 23:01 UTC
When I try to unlock or edit an existing slug for a page in the secondary language, either the changed information doesn't save, or the page reloads, which resets the lock. only the slug of the main language can be edited this way.

php 7.2, bolt 4 release5

english locale slug == 'introduction' (see other issue)
![wrongslug](https://user-images.githubusercontent.com/21077532/75105085-3a411d00-5611-11ea-9abe-028538111be1.png)

**Comment by 0spinboson** [comment] 2020-02-23 17:19
to add/clarify: I've set up the contenttype homepage as is (i.e., with no localize:true set for the slug). But when you switch locale, it displays a different slug from the one I set in the main locale, and you can't change that because localize isn't defined / set to false.

**Comment by I-Valchev** [comment] 2020-02-24 08:21
I used a fresh install, with fixtures. The homepage does not have
```
slug:
   localize: true
```
which as you point out means that the slug is the same across all locales. The expected behaviour is that you may see and edit the slug from any locale, and this will be updated across all languages.

I was not able to reproduce this issue. However, I was able to reproduce the issue with the page reloading. For me that happens in this order:

1. Click "Locked" dropdown
2. Select "Locked" (not sure if this needs to be there at this point
3. Click "Locked" dropdown again
4. Click "Edit"

At this point the page reloads, which as you say prevents you from editing the locale. I'll look into this now :-)

**Comment by I-Valchev** [comment] 2020-02-24 09:26
A fix for the reload bug is in the pipeline #1118

**Comment by bobdenotter** [comment] 2020-02-25 05:40
Fixed in #1118

**Closed by bobdenotter** 2020-02-25 05:40 UTC
