### ISSUE TITLE
nbsp issues in the html and redactor WYSIWYG editors

### ISSUE THREAD

**Issue by 0spinboson** [bolt/core#1755] opened 2020-08-22 21:17 UTC
using rc36 atm, but the issue's been around for a very long time, including in bolt 3.x.
When I use the html or redactor WYSIWYG editors, and I add a space around a section with <em></em> around it, it almost always records these spaces as nbsps. This behavior seems to me undesirable.

(It also occurs in a few other cases, but I haven't figured out the logic yet.)

**Comment by 0spinboson** [comment] 2020-08-25 10:13
Oh, is that how you're supposed to be able to force it? Ugh. Maybe that's the explanation sometimes, then. 
Anyway, I found a reliable way to reproduce the behavior I don't want: "<em>text,</em> lalala" then shift-select the space only, and type a space. outcome: "<em>text,&nbsp;</em>lalala".

**Comment by 0spinboson** [comment] 2020-09-11 06:13
I would guess that most of the time, I'm creating them by redacting text (I tend to delete words using ctrl-delete/backspace, leading to the spaces 'meeting' as the feature isn't clever enough to also remove a space. That said, I do think that the behavior described above (with italicized text) is a bug. But if this is something that's intended as a "feature", I should probably report it upstream somewhere?

**Comment by bobdenotter** [comment] 2020-09-11 06:18
I'm not sure.. I've still never seen this happen.. 

> leading to the spaces 'meeting' as the feature isn't clever enough to also remove a space.

So.. Are you saying you actually have two spaces between words? In that case, having `&nbsp;`'s is the actual expected behaviour. If you input two spaces, it _needs_ to use nbsp's to keep them as is. If you _don't_ want double spaces, then don't input double spaces. :-)

**Comment by 0spinboson** [comment] 2020-09-11 06:30
no, but in word / liberoffice offline editors, when you ctrl-delete a word, it also deletes the space after (or before) it. here it only deletes the word itself, and so the space that was left of the word meets the space on the right, which creates a double space -> nbsp, which then become nbsps on both sides of the new word I type in to replace the ctrl-backspaced one.

**Comment by bobdenotter** [comment] 2020-09-20 06:29
I've marked this as "third party" and "not a bug". It's something that's not directly under our control (seeing as how it happens in Trumbowyg, CKeditor _and_ in the new Article and Redactor. 

Apart from that, i think they won't classify it as a bug, because it may not be the desired behaviour, but it _does_ do what it's told: If you input two spaces, you *get* two spaces. :-)

**Comment by bobdenotter** [comment] 2020-09-20 06:31
I've marked this as "third party" and "not a bug". It's something that's not directly under our control (seeing as how it happens in Trumbowyg, CKeditor _and_ in the new Article and Redactor). 

Apart from that, i think they won't classify it as a bug, because it may not be the desired behaviour, but it _does_ do what it's told: If you input two spaces, you *get* two spaces. :-)

**Closed** 2024-02-07 00:27 UTC
Labels: Topic: Third Party 🖇, 👻 Not a bug
