### ISSUE TITLE
gument 1 passed to Bolt\Twig\ContentExtension::getListTemplates() must be an instance of Bolt\Entity\Field\TemplateselectField

### ISSUE THREAD

**Issue by hanzx** [bolt/core#2086] opened 2020-11-01 10:28 UTC
When i want add new page:

`[2020-11-01T11:24:44.900554+01:00] php.CRITICAL: Uncaught Error: Argument 1 passed to Bolt\Twig\ContentExtension::getListTemplates() must be an instance of Bolt\Entity\Field\TemplateselectField, instance of Bolt\Entity\Field given, called in /data/web/virtuals/244639/virtual/www/var/cache/prod/twig/08/080156bd5c10d7ab5471c628e6aa07935d94bd5acd4878eeb19c3b0454a6ff98.php on line 42 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Bolt\\Twig\\ContentExtension::getListTemplates() must be an instance of Bolt\\Entity\\Field\\TemplateselectField, instance of Bolt\\Entity\\Field given, called in /data/web/virtuals/244639/virtual/www/var/cache/prod/twig/08/080156bd5c10d7ab5471c628e6aa07935d94bd5acd4878eeb19c3b0454a6ff98.php on line 42 at /data/web/virtuals/244639/virtual/www/vendor/bolt/core/src/Twig/ContentExtension.php:480)"} []`

**Comment by bobdenotter** [comment] 2020-11-01 11:38
This is a duplicate of https://github.com/bolt/core/issues/2030. See there for more info.

**Closed by bobdenotter** 2020-11-01 11:38 UTC
